[package]
name = "vigier"
version = "0.1.1"
authors = ["Silvio Henrique Ferreira <shferreira@me.com>"]
license = "MIT"
description = "Lightweight game library"
edition = "2018"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = true
opt-level = 's'

[package.metadata.bundle]
name = "Vigier"
