name: Rust

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add x86_64-apple-ios aarch64-apple-ios
      - run: cargo install --path .
      - run : cargo appify macos --release
      - run : cargo appify ios --release
      - run : cargo appify web --release
      - uses: actions/upload-artifact@v2
        with:
          name: vigier-macos
          path: |
            target/ios/App.app
            target/macos/App.app
            target/web/App.*
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add i686-unknown-linux-gnu x86_64-unknown-linux-gnu wasm32-unknown-unknown i686-linux-android x86_64-linux-android armv7-linux-androideabi aarch64-linux-android
      - run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libc6-dev libc6-dev-i386 mesa-common-dev libgl1-mesa-dev libgl1 mesa-common-dev:i386 libgl1-mesa-dev:i386 libgl1:i386 libasound2-dev libasound2-dev:i386
      - run: cargo install --path .
      - run: cargo appify x11 --release
      - run: cargo appify android --release
      - uses: actions/upload-artifact@v2
        with:
          name: vigier-linux
          path: |
            target/android/App
            target/x11/App
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cargo install --path .
      - run: cargo appify win --release
      - uses: actions/upload-artifact@v2
        with:
          name: vigier-win32
          path: target/win/App.exe
